name: cctv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pytorch=1.13.0
  - torchvision=0.14.0
  - pytorch-cuda=11.6
  - cudatoolkit=11.6
  - cudnn=8.4.0
  - opencv>=4.7.0
  - numpy=1.23.5
  - pandas>=1.5.3
  - matplotlib>=3.7.1
  - pillow>=9.4.0
  - scipy=1.9.3
  - tqdm>=4.65.0
  - pyyaml>=6.0
  - requests>=2.28.2
  - psutil>=5.9.0
  - setuptools<60.0
  - pip:
    - ultralytics>=8.0.0
    - bytetracker>=0.3.2
    - torchreid==0.2.5
    - lap==0.4.0
    - scikit-image==0.19.3
    - filterpy>=1.4.5
    - cython>=0.29.33
    - easydict>=1.10
    - motmetrics>=1.4.0
    - loguru>=0.7.0
    - torchsummary>=1.5.1
    - gdown
    - tensorboard

# Optional dependencies for development
  - ipython
  - jupyter