name: cctv-analysis
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ipykernel
  - pip
  - numpy>=1.21.0
  - opencv>=4.5.3
  - pandas>=1.3.0
  - matplotlib>=3.4.2
  - tqdm>=4.61.0
  - pillow>=8.2.0
  - scipy>=1.7.0
  - pyyaml>=5.4.1
  - ipython>=7.25.0
  - jupyter>=1.0.0
  - git>=2.33.0
  - GPUtil
  - pip:
    # Install PyTorch with CUDA 12.1 support
    - torch==2.1.2+cu121
    - torchvision==0.16.2+cu121
    - torchaudio==2.1.2+cu121 
    - --extra-index-url https://download.pytorch.org/whl/cu121
    - git+https://github.com/Megvii-BaseDetection/YOLOX.git
    - insightface>=0.1.0
    - torchreid==0.2.5
    - wget>=3.2
    - gdown>=5.2.0
    - onnxruntime-gpu>=1.9.0
    - seaborn>=0.11.1
    - ultralytics
    - huggingface_hub>=0.0.12
    - -e .  # Install the current directory as a package
