name: cctv-analysis
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ipykernel
  - pip
  - numpy>=1.21.0
  - pytorch>=1.9.0
  - torchvision
  - cudatoolkit=12.0  # Adjust version based on your CUDA version
  - opencv>=4.5.3
  - pandas>=1.3.0
  - matplotlib>=3.4.2
  - tqdm>=4.61.0
  - pillow>=8.2.0
  - scipy>=1.7.0
  - pyyaml>=5.4.1
  - ipython>=7.25.0
  - jupyter>=1.0.0
  - git
  - pip:
    - git+https://github.com/Megvii-BaseDetection/YOLOX.git
    - insightface>=0.1.0
    - torchreid>=0.2.5
