from setuptools import find_packages, setup

setup(
    name="cctv_analysis",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.19.0",
        "pandas>=1.3.0",
        "opencv-python>=4.5.0",
        "torch>=1.9.0",
        "torchvision>=0.10.0",
        "deepface>=0.0.75",
        "matplotlib>=3.3.0",
        "seaborn>=0.11.0",
        "plotly>=5.3.0",
        "pyyaml>=5.4.1",
        "scipy>=1.7.0",
        "scikit-learn>=0.24.0",
        "jinja2>=3.0.0",
        "pdfkit>=1.0.0",
        "pillow>=8.0.0",
    ],
    extras_require={
        "dev": [
            "pytest>=6.2.5",
            "pytest-cov>=2.12.0",
            "black>=21.5b2",
            "flake8>=3.9.0",
            "isort>=5.9.0",
            "mypy>=0.910",
            "pre-commit>=2.15.0",
        ]
    },
    author="Your Name",
    author_email="your.email@example.com",
    description="A comprehensive CCTV analysis system for tracking individuals across multiple cameras",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/cctv-analysis",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.12",
    ],
    python_requires=">=3.8",
)
