# Default configuration for CCTV Analysis System

# System-wide settings
system:
  version: "0.1.0"
  base_dir: "output"
  temp_dir: "temp"
  enable_gpu: true
  num_workers: 4
  batch_size: 32

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  console: true
  file:
    enabled: true
    directory: "logs"
    max_size_mb: 100
    backup_count: 5
    rotate_when: "midnight"

# Person detection settings
detector:
  backend: "yolov5"  # yolov5, ssd, hog
  model_path: "models/yolov5s.pt"
  confidence_threshold: 0.5
  device: "cuda"  # cuda, cpu
  input_size: [640, 640]
  batch_size: 16
  nms_threshold: 0.45
  class_filters: [0]  # 0 is person class in COCO
  augmentation:
    enabled: false
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2

# Person tracking settings
tracker:
  max_disappeared: 30
  max_distance: 0.6
  min_confidence: 0.5
  feature_extractor:
    model: "resnet50"
    weights: "models/feature_extractor.pth"
    input_size: [256, 128]
  matching:
    method: "hungarian"  # hungarian, greedy
    max_iou_distance: 0.7
    max_age: 30
    n_init: 3
    max_features: 100

# Demographic analysis settings
demographics:
  enabled: true
  batch_size: 32
  backend: "opencv"  # opencv, dlib, mtcnn
  models:
    age:
      enabled: true
      model_path: "models/age_net.caffemodel"
      confidence_threshold: 0.6
    gender:
      enabled: true
      model_path: "models/gender_net.caffemodel"
      confidence_threshold: 0.6
  age_groups:
    - [0, 18]
    - [19, 35]
    - [36, 50]
    - [51, 100]

# Video processing settings
video:
  input:
    max_resolution: [1920, 1080]
    fps: 30
    format: "mp4"
  output:
    enabled: true
    format: "mp4"
    fps: 30
    resolution: [1280, 720]
    codec: "mp4v"
    quality: 95
  processing:
    skip_frames: 1
    buffer_size: 64
    enable_preprocessing: true
    preprocessing:
      resize: true
      denoise: false
      normalize: true

# Data storage settings
storage:
  format: "csv"  # csv, json, sqlite
  compression: false
  backup:
    enabled: true
    interval: "1d"
    keep_days: 30
  database:
    type: "sqlite"
    path: "data/cctv_analysis.db"
    backup_enabled: true

# Visualization settings
visualization:
  enabled: true
  style: "seaborn"
  output_format: "png"  # png, jpg, svg
  dpi: 300
  interactive: true
  plots:
    traffic_flow:
      enabled: true
      type: "line"
      height: 600
      width: 800
    demographics:
      enabled: true
      type: "bar"
      height: 500
      width: 700
    movement_patterns:
      enabled: true
      type: "heatmap"
      height: 600
      width: 800
    dwell_time:
      enabled: true
      type: "box"
      height: 400
      width: 600

# Report generation settings
reports:
  formats:
    - html
    - pdf
    - json
  template_dir: "templates"
  output_dir: "reports"
  include_visualizations: true
  pdf:
    page_size: "A4"
    orientation: "portrait"
    fonts:
      - "Arial"
      - "Times New Roman"
  html:
    theme: "default"
    include_interactive: true
    responsive: true

# Performance monitoring
monitoring:
  enabled: true
  metrics:
    - cpu_usage
    - memory_usage
    - gpu_usage
    - processing_time
  alert_thresholds:
    cpu_usage: 90
    memory_usage: 85
    gpu_usage: 95
  logging_interval: 60  # seconds

# Privacy settings
privacy:
  face_blur: true
  data_retention_days: 30
  encryption:
    enabled: true
    algorithm: "AES"
    key_file: "config/encryption_key.key"
  anonymization:
    enabled: true
    methods:
      - face_blur
      - id_hash
    blur_kernel_size: [23, 23]

# Error handling
error_handling:
  retry_attempts: 3
  retry_delay: 5  # seconds
  fallback_detection: "hog"
  error_notification:
    enabled: true
    methods:
      - log
      - email
  critical_errors:
    - detector_failure
    - tracker_failure
    - database_connection

# API settings (if needed)
api:
  enabled: false
  host: "localhost"
  port: 8000
  rate_limit: 100
  timeout: 30
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  authentication:
    enabled: true
    method: "jwt"
    token_expiry: "24h"
