# Model configurations for CCTV Analysis

models:
  detector:
    name: "YOLOX-L"
    version: "0.1.1rc0"
    url: "https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_l.pth"
    output_path: "detector/yolox_l.pth"  # Relative to models directory
    md5: "87592389624fa3963c929a3fd01cbf8f"
    size_mb: 155.4
    source_type: "direct"
    required: true
    description: "YOLOX large model for person detection"
    paper_url: "https://arxiv.org/abs/2107.08430"

  reid:
    name: "OSNet"
    version: "1.0.0"
    url: "https://drive.google.com/uc?id=1vduhq5DpN2q1g4fYEZfPI17MJeh9qyrA"
    output_path: "reid/osnet_x1_0.pth"  # Relative to models directory
    source_type: "gdrive"
    size_mb: 73.2
    required: true
    description: "OSNet model for person re-identification"
    paper_url: "https://arxiv.org/abs/1905.00953"

download_settings:
  chunk_size: 8192
  retry_count: 3
  timeout: 30
  verify_ssl: true
  progress_bar: true
  gdrive:
    cookies_file: ".gdrive_cookies"  # Temporary file for Google Drive cookies

paths:
  base_dir: "./models"  # Base models directory
  temp_dir: ".temp"     # Relative to base_dir
  backup_dir: ".backup" # Relative to base_dir